### PR TITLE
Fixing link for "mal"

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @razum2um 

just fixing a link here...

Cheers!

### CODE REVIEW

**Comment by razum2um** [comment]
thanks for paying attention, but the idea was to point to https://github.com/kanaka/mal/tree/master/impls/clojure

**Comment by spekulatius** [comment]
One second, I'll update it @razum2um

**Comment by spekulatius** [comment]
Done @razum2um

**Comment by razum2um** [comment]
thanks!

**Comment by spekulatius** [comment]
Awesome, thanks for merging!

**Pull request merged**
